version: '3'
services:
  db:
    container_name: doctober_cms_db
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DOCTOBER_CMS_DB_DATABASE}
      - MYSQL_USER=${DOCTOBER_CMS_DB_USERNAME}
      - MYSQL_PASSWORD=${DOCTOBER_CMS_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DOCTOBER_CMS_DB_PASSWORD}

  php:
    container_name: doctober_cms_php
    build:
      context: ./php
    volumes:
      - "../:/var/www/app"
    links:
      - db

  nginx:
    container_name: doctober_cms_nginx
    image: nginx:latest
    ports:
      - "${DOCTOBER_CMS_NGINX_PORT}:80"
    volumes:
      - "./nginx/logs:/var/log/nginx"
#      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/default.template:/etc/nginx/conf.d/default.template"
      - "../:/var/www/app"
    environment:
      - NGINX_HOST=${DOCTOBER_CMS_NGINX_HOST}
      - NGINX_PORT=${DOCTOBER_CMS_NGINX_PORT}
      - PHP_FPM_HOST=doctober_cms_php
      - PHP_FPM_PORT=${DOCTOBER_CMS_PHP_FPM_PORT}
      - TZ=${DOCTOBER_CMS_TIMEZONE}
    links:
      - php